sequenceDiagram
    actor Worker
    participant TaskCard as TaskCardComponent
    participant EventPage as EventViewerPage
    participant TaskService as TaskServiceServer
    participant API as TaskController
    participant Repo as TaskRepository
    participant DB as MongoDB

    Worker->>TaskCard: Ændre status i dropdown menuen
    activate TaskCard
    TaskCard->>TaskCard: OnStatusChanged()
    Note over TaskCard: Opdatere status lokalt øjeblikket
    
    TaskCard->>TaskService: UpdateTaskStatus(taskId, newStatus)
    activate TaskService
    
    TaskService->>API: PUT /task/{id}
    activate API
    
    API->>Repo: UpdateAsync(task)
    activate Repo
    
    Repo->>DB: Gem status i Databasen
    activate DB
    DB-->>Repo: Returner status
    deactivate DB
    
    Repo-->>API: Opgave status udført
    deactivate Repo
    
    API-->>TaskService: 200 OK
    deactivate API
    
    TaskService-->>TaskCard: true
    deactivate TaskService
    
    TaskCard->>EventPage: OnTaskStatusUpdated.InvokeAsync()
    activate EventPage
    EventPage-->>TaskCard: Anerkendt
    deactivate EventPage
    
    TaskCard-->>Worker: Status opdateret (visuelt)
    deactivate TaskCard
