using System.Collections.Generic;                                                                                                                                                                                                                                                                                                                                          
 using System.Linq;                                                                                                                                                                                                                                                                                                                                                         
 using System.Threading.Tasks;                                                                                                                                                                                                                                                                                                                                              
 using core.Models;                                                                                                                                                                                                                                                                                                    
 using webapp.Service;                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                            
 public class TaskServiceInMemory : ITaskService                                                                                                                                                                                                                                                                                                                            
 {                                                                                                                                                                                                                                                                                                                                                                          
     private readonly List<TaskItem> _tasks = new List<TaskItem>();                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                            
     public Task<bool> CreateTaskAsync(TaskItem newTaskItem)                                                                                                                                                                                                                                                                                                                
     {                                                                                                                                                                                                                                                                                                                                                                      
         _tasks.Add(newTaskItem);                                                                                                                                                                                                                                                                                                                                           
         return Task.FromResult(true);                                                                                                                                                                                                                                                                                                                                      
     }                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                            
     public Task<bool> EditTaskAsync(int id, TaskItem updateTaskItem)                                                                                                                                                                                                                                                                                                       
     {                                                                                                                                                                                                                                                                                                                                                                      
         var task = _tasks.FirstOrDefault(t => t.Id == id);                                                                                                                                                                                                                                                                                                                 
         if (task != null)                                                                                                                                                                                                                                                                                                                                                  
         {                                                                                                                                                                                                                                                                                                                                                                  
             // Update the task properties here                                                                                                                                                                                                                                                                                                                             
             task.Title = updateTaskItem.Title;                                                                                                                                                                                                                                                                                                                               
             task.Description = updateTaskItem.Description;                                                                                                                                                                                                                                                                                                                 
             // Add other properties as needed                                                                                                                                                                                                                                                                                                                              
             return Task.FromResult(true);                                                                                                                                                                                                                                                                                                                                  
         }                                                                                                                                                                                                                                                                                                                                                                  
         return Task.FromResult(false);                                                                                                                                                                                                                                                                                                                                     
     }                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                            
     public Task<List<TaskItem>> LoadAllTask()                                                                                                                                                                                                                                                                                                                              
     {                                                                                                                                                                                                                                                                                                                                                                      
         return Task.FromResult(_tasks);                                                                                                                                                                                                                                                                                                                                    
     }                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                            
     public Task<TaskItem> GetTaskAsync(int id)                                                                                                                                                                                                                                                                                                                             
     {                                                                                                                                                                                                                                                                                                                                                                      
         var task = _tasks.FirstOrDefault(t => t.Id == id);                                                                                                                                                                                                                                                                                                                 
         return Task.FromResult(task);                                                                                                                                                                                                                                                                                                                                      
     }                    
     
     public Task<List<TaskItem>> GetTasksByEventIdAsync(int eventId)                                                                                                                                                                                                                                                                                                     
     {                                                                                                                                                                                                                                                                                                                                                                   
         var tasksForEvent = _tasks.Where(t => t.EventId == eventId).ToList();                                                                                                                                                                                                                                                                                           
         return Task.FromResult(tasksForEvent);                                                                                                                                                                                                                                                                                                                          
     }    

     public Task<bool> DeleteTaskAsync(int id)
     {
         var task = _tasks.FirstOrDefault(t => t.Id == id);
         if (task != null)
         {
             _tasks.Remove(task);
             return Task.FromResult(true);
         }
         return Task.FromResult(false);
     }
 } 
