name: Deploy to Azure
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      # Build and publish server
      - name: Clean Server
        run: dotnet clean ./Server.sln

      - name: Restore Server dependencies
        run: dotnet restore ./Server.sln

      - name: Build Server
        run: dotnet build ./Server.sln --configuration Release --no-restore
      
      - name: Publish Server
        run: dotnet publish ./Server.sln -c Release -o ${{env.DOTNET_ROOT}}/server

      # Build and publish webapp
      - name: Clean Webapp
        run: dotnet clean ./Webapp.sln

      - name: Restore Webapp dependencies
        run: dotnet restore ./Webapp.sln

      - name: Build Webapp
        run: dotnet build ./Webapp.sln --configuration Release --no-restore
      
      - name: Publish Webapp
        run: dotnet publish ./Webapp.sln -c Release -o ${{env.DOTNET_ROOT}}/webapp
      
      # Deploy Server (Development)
      - name: Deploy Server to Azure Web App (Development)
        if: github.ref == 'refs/heads/dev'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kantinen-server-dev'
          publish-profile: ${{ secrets.AZURE_SERVER_PUBLISH_PROFILE_API_DEV}}
          package: ${{env.DOTNET_ROOT}}/server
      
      # Deploy Blazor App (Development)
      - name: Deploy Blazor to Azure Web App (Development)
        if: github.ref == 'refs/heads/dev'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kantinen-webapp-dev'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_APP_DEV}}
          package: ${{env.DOTNET_ROOT}}/webapp
