name: CI Check

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple check
        run: echo "This is a simple status check!"
