name: Server Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test Server
      env:
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      run: |
        dotnet run --project server/server.csproj --no-build &
        sleep 10
        curl -f http://localhost:5267/Test/
